# Generated by Django 5.1.2 on 2026-08-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='recruiter_feedback',
            field=models.TextField(blank=True),
        ),
    ]
